export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const LOAD_ALL_ARTICLES_START = 'LOAD_ALL_ARTICLES_START'
export const LOAD_ALL_ARTICLES_FAIL = 'LOAD_ALL_ARTICLES_FAIL'
export const LOAD_ALL_ARTICLES_SUCCESS = 'LOAD_ALL_ARTICLES_SUCCESS'